### ISSUE TITLE
Feature request: CauseWay decompression

### ISSUE THREAD

**Issue by neuromancer** [tkchia/causeway#2]
I'm wondering if `cwd` is planed for this neat port.

**Comment by tkchia** [comment]
Hello @neuromancer,

Not yet, I guess. :neutral_face:

I have just started exploring the CauseWay code, so there is a lot I have yet to learn about it.  Anyway, apparently `cwd.exe` in the source tree is actually a _debugger_ (not decompressor) for CauseWay programs, and for now I do not know if there is actually any utility to "unpack" compressed CauseWay executables.  Perhaps it will be useful to write one. :slightly_smiling_face: 

Thank you!

**Comment by tkchia** [comment]
(It seems that CauseWay's `cwc.exe` &mdash; but not the Watcom `cwc.exe` &mdash; might actually have unpacker functionality.  If so, then I should probably at least try to get it to build and run under MS-DOS.)

Thank you!

**Comment by tkchia** [comment]
Hello @neuromancer,

I am now _almost_ able to rebuild the `cwc.exe` CauseWay (de-)compressor program from sources &mdash; except for one thing.

To build `cw.lib`, which `cwc.exe` needs, I need a librarian program which can create [OMF](https://en.wikipedia.org/wiki/Relocatable_Object_Module_Format) library (`.lib`) files, and which (hopefully) I can conveniently compile from source code.

OK, there is `wlib` from [Open Watcom](https://github.com/open-watcom/open-watcom-v2) compiler kit, but it itself needs to be compiled as part of the humongous Open Watcom source tree.

Thank you!

**Comment by tkchia** [comment]
> > To build `cw.lib`, which `cwc.exe` needs, I need a librarian program which can create [OMF](https://en.wikipedia.org/wiki/Relocatable_Object_Module_Format) library (`.lib`) files, and which (hopefully) I can conveniently compile from source code.

Perhaps the `xlib` program in [David Lindauer's `cc386` toolchain](https://ladsoft.tripod.com/cc386_compiler.html) might be able to do this. :slightly_smiling_face:   I (or we) will have to see...

Thank you!

**Comment by tkchia** [comment]
Hello @neuromancer,

I am now able to rebuild the `cwc.exe` CauseWay compressor &mdash; which includes a decompressor &mdash; from sources, and it works.

There is just one nit though: while it can directly decompress `CWC` data files, it cannot directly decompress CauseWay program (i.e. `.exe`) files:
![image](https://user-images.githubusercontent.com/5507843/215340240-17744bf1-89b5-46ad-9565-08602e0f5cc4.png)

But you might be able to decompress an `.exe` file by looking for the individual `CWC` blocks inside and expanding them.  Anyway, is decompressing `.exe` files is something you might need (or want)?

Thank you!

**Comment by neuromancer** [comment]
Hi, thanks for taking the time to follow and fix this issue! I will check exactly what I needed to decompress and get back to you.

**Comment by neuromancer** [comment]
My original idea what to decompress an exe file. This is not a priority anymore, since I used dosbox to dump the complete memory once it is decompressed and that was enough for the reverse engineering I needed. However, I can still provide the exe if you want to have real example of game compressed with CauseWay, in case you want to test this new feature.

**Comment by tkchia** [comment]
Hello @neuromancer,

Thanks for your offer.  I think I should be able to produce (or find) some compressed executables to work as test cases.  But if I might need your help, I will be sure to let you know. :slightly_smiling_face:  Thank you!
