### ISSUE TITLE
GetSystemFlags doesn't propagate error

### ISSUE THREAD

**Issue by stsp** [tkchia/causeway#4]
GetSystemFlags opens an exe file and
reads the flags from it. The error is however
not propagated. If open fails, the bunch of
strange behavior happens, eg it starts in
32bit DPMI mode instead of 16bit because
the flags also indicate the needed DPMI mode.
I think something like this (compile-tested
only) patch might be a fix:
```
diff --git a/source/all/cw32.asm b/source/all/cw32.asm
index 29c3947..7ef4efe 100644
--- a/source/all/cw32.asm
+++ b/source/all/cw32.asm
@@ -832,6 +832,7 @@ chk386:
 ;Retrieve setup info from 3P header.
 ;
         call    GetSystemFlags
+        jc      InitError
 ;
 ;Check if a suitable method for switching to protected mode exists.
 ;
@@ -4421,6 +4422,7 @@ medexe2:
 @@sr5:  pop     es
         ;
         assume ds:_cwMain
+        clc
 @@5:    pop     ds
         ret
 GetSystemFlags  endp
```

**Comment by tkchia** [comment]
Hello @stsp,

How can I reproduce this problem?  I have not been able to contrive a situation where a CauseWay `.exe` starts up but for some reason cannot go back to read itself.

Thank you!

**Comment by stsp** [comment]
The thing is, in this case cw uses
share open, whereas in all other
places it uses compat open. So
to reproduce, you can for example
comment out mfs.c:694:
`err = open_share(fd, flags, share_mode);`
replacing it with `err = 1` or alike.
Initially the problem happened because
dosemu2 had a leak of share resources
on reboot. So after ~100 reboots cw
started to consistently crash, and that
lead me to investigate.

**Comment by tkchia** [comment]
@stsp : this should be fixed with https://github.com/tkchia/causeway/commit/681d25930a63a2f98c2150bf9de3ec2ffb3f06b3 .  Thank you!
